name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init (no backend)
        run: terraform -chdir=infra/terraform init -backend=false -input=false -upgrade
      - name: Terraform Validate
        run: terraform -chdir=infra/terraform validate -no-color

  audit:
    runs-on: ubuntu-latest
    needs: terraform
    env:
      DEPLOY_URL: ${{ env.DEPLOY_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build web
        run: pnpm --filter ./apps/web build
      - name: Lighthouse CI
        run: |
          pnpm --filter ./apps/web start -- -p 3000 &
          SERVER_PID=$!
          sleep 10
          npx lighthouse-ci http://localhost:3000 --score=95
          kill $SERVER_PID
      - name: OWASP ZAP Baseline
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t $DEPLOY_URL -m 0 -r zap.html
